Add Chapter "Debugging with CCPP"
NCAR/ccpp-doc pull request #24
Opened 2020-09-12 18:45 UTC by bluefinweiwei

new file:   source/CCPPDebug.rst	
modified:   source/index.rst

2020-09-12 20:41 UTC, climbfuji commented
Did you create the documentation with those changes? Is it available somewhere for me to look at it? cheyenne or hera would do. Thanks ...

2020-09-12 20:45 UTC, bluefinweiwei commented
Yep. Here they are: /glade/u/home/weiweili/my_work/GMTB/ccpp-doc/CCPPtechnical/source

Thanks!

2020-09-12 20:45 UTC, bluefinweiwei commented
> Did you create the documentation with those changes? Is it available somewhere for me to look at it? cheyenne or hera would do. Thanks ...

Yep. Here they are: /glade/u/home/weiweili/my_work/GMTB/ccpp-doc/CCPPtechnical/source

Thanks!

2020-09-12 20:51 UTC, climbfuji commented
What I meant to ask was if you had created the `.html` and/or `.pdf` versions to look at, sorry.

2020-09-12 20:54 UTC, bluefinweiwei commented
> What I meant to ask was if you had created the `.html` and/or `.pdf` versions to look at, sorry.

I built all these on my laptop. Now they should have been updated on Cheyenne. Please check /glade/u/home/weiweili/my_work/GMTB/ccpp-doc/CCPPtechnical/build/html

Thanks!

2020-09-12 21:02 UTC, climbfuji requested changes

2020-09-12 21:02 UTC, climbfuji commented on CCPPtechnical/source/CCPPDebug.rst
> +    All output to ``stdout/stderr`` from this routine is prefixed with **'XXX: '** so that it can be easily removed from the log files using "grep -ve 'XXX: ' ..." if needed.
This sentence ended up in the code block in the html version - needs to be regular text.

2020-09-13 02:50 UTC, ligiabernardet commented
Can also be viwed at
https://weiwei-techdoc.readthedocs.io/en/latest/ParamSpecificOutput.html
Note: there is no repo hook. If Weiwei makes changes to her branch/PR, I
need to trigger a new build manually.

On Sat, Sep 12, 2020 at 3:03 PM Dom Heinzeller <notifications@github.com>
wrote:

> *@climbfuji* requested changes on this pull request.
> ------------------------------
>
> In CCPPtechnical/source/CCPPDebug.rst
> <https://github.com/NCAR/ccpp-doc/pull/24#discussion_r487448521>:
>
> > +         call print_var(mpirank, omprank, blkno, Grid%xlat_d, Grid%xlon_d, 'Diag%srunoff', Diag%srunoff)
> +         ...
> +         ! Statein
> +         call print_var(mpirank, omprank, blkno, Grid%xlat_d, Grid%xlon_d, 'Statein%phii', Statein%phii)
> +         ! Stateout
> +         call print_var(mpirank, omprank, blkno, Grid%xlat_d, Grid%xlon_d, 'Stateout%gu0', Stateout%gu0)
> +         ...
> +         ! Coupling
> +         call print_var(mpirank, omprank, blkno, Grid%xlat_d, Grid%xlon_d, 'Coupling%nirbmdi', Coupling%nirbmdi)
> +         ...
> +         ! Grid
> +         call print_var(mpirank, omprank, blkno, Grid%xlat_d, Grid%xlon_d, 'Grid%xlon', Grid%xlon)
> +         ...
> +         end subroutine GFS_diagtoscreen_run
> +
> +    All output to ``stdout/stderr`` from this routine is prefixed with **'XXX: '** so that it can be easily removed from the log files using "grep -ve 'XXX: ' ..." if needed.
>
> This sentence ended up in the code block in the html version - needs to be
> regular text.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/NCAR/ccpp-doc/pull/24#pullrequestreview-487256369>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE7WQAXVK3RZ4HEQUGPVQLLSFPOYXANCNFSM4RJ2VJEA>
> .
>

2020-09-13 02:55 UTC, climbfuji commented
> Can also be viwed at https://weiwei-techdoc.readthedocs.io/en/latest/ParamSpecificOutput.html Note: there is no repo hook. If Weiwei makes changes to her branch/PR, I need to trigger a new build manually.
> […](#)

Thanks, this page doesn't have the new chapter 11 yet.

2020-09-13 03:11 UTC, ligiabernardet commented
Try this: https://weiwei-techdoc.readthedocs.io/en/ccpp_debug/

On Sat, Sep 12, 2020 at 8:55 PM Dom Heinzeller <notifications@github.com>
wrote:

> Can also be viwed at
> https://weiwei-techdoc.readthedocs.io/en/latest/ParamSpecificOutput.html
> Note: there is no repo hook. If Weiwei makes changes to her branch/PR, I
> need to trigger a new build manually.
> … <#m_-1663712134230055993_>
>
> Thanks, this page doesn't have the new chapter 11 yet.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/NCAR/ccpp-doc/pull/24#issuecomment-691598690>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE7WQAQ34ZIHUVUGGUISM23SFQYDNANCNFSM4RJ2VJEA>
> .
>

2020-09-13 03:33 UTC, ligiabernardet requested changes
Looks good, just need some minor fixes.

2020-09-13 03:33 UTC, ligiabernardet commented on CCPPtechnical/source/CCPPDebug.rst
> +How to use these debugging schemes for the UFS?
```suggestion
How to use these debugging schemes for the UFS
```

2020-09-13 03:33 UTC, ligiabernardet commented on CCPPtechnical/source/CCPPDebug.rst
> +    For example, the Unified Forecast System (UFS) models use blocked data structures, which - at present - requires different debugging schemes for the ``time_vary`` group in the SDF. The blocked da
UFS already defined in previous chapter
```suggestion
    For example, the UFS models use blocked data structures, which - at present - requires different debugging schemes for the ``time_vary`` group in the SDF. The blocked data structures are commonly known as “GFS types”, are defined in ``GFS_typedefs.F90`` and exposed to the CCPP in ``GFS_typedefs.meta``. The rationale for this storage model is a better cache reuse by breaking up contiguous horizontal grid columns into N blocks with a predefined block size, and allocating each of the GFS types N times. For example, the 3-dimensional air temperature is stored as
```

2020-09-13 03:33 UTC, ligiabernardet commented on CCPPtechnical/source/CCPPDebug.rst
> +Traditional, physics-driver based approaches rely on hand-written physics drivers that connect the different physical parameterizations together and often contain a large amount of "glue code" requir
SDF already defined in previous chapter
```suggestion
Traditional, physics-driver based approaches rely on hand-written physics drivers that connect the different physical parameterizations together and often contain a large amount of "glue code" required between the parameterizations. As such, the physics drivers usually have access to all variables that are used by the physical parameterizations, while individual parameterizations only have access to the variables that are passed in. Debugging either happens on the level of the physics driver or inside physical parameterizations. In both cases, print statements are inserted in one or more places (e.g. in the driver before/after parameterizations to debug). In the CCPP, there are no hand-written physics drivers. Instead, the physical parameterizations are glued together by a SDF that lists the primary physical parameterizations and so-called interstitial parameterizations (containing the glue code, broken up into logical units) in the order of execution.
```

2020-09-14 01:09 UTC, bluefinweiwei commented on CCPPtechnical/source/CCPPDebug.rst
> +    All output to ``stdout/stderr`` from this routine is prefixed with **'XXX: '** so that it can be easily removed from the log files using "grep -ve 'XXX: ' ..." if needed.
Thanks for catching that! It should have been fixed now.

2020-09-14 01:10 UTC, bluefinweiwei commented
> Looks good, just need some minor fixes.

All should have been fixed. Let me know of anything else to be revised. Thank you both for the review! :)

2020-09-14 02:19 UTC, ligiabernardet approved these changes

2020-09-14 13:25 UTC, climbfuji approved these changes

2020-09-14 13:25 UTC, climbfuji commented
@JulieSchramm do you want to take a look as well before I merge this? Thanks!

2020-09-14 14:55 UTC, JulieSchramm approved these changes
Looks good!

2020-09-14 14:56 UTC, merged