Update doc to include [ccpp-table-properties]:
NCAR/ccpp-doc pull request #28
Opened 2020-10-15 17:45 UTC by JulieSchramm

- Update CCPPPreBuild.rst and _static/ccpp_prebuild_static_only.png to remove
    SCHEME_FILES_DEPENDENCIES and update example of ccpp_prebuild_config.py for SCM

  - Update CompliantPhysicsParams.rst to include [ccpp-table-properties] and
    update listings to include this new table section

  - Remove CCPP=N from ConfigBuildOptions.rst

  - Update HostSideCoding.rst to include [ccpp-table-properties]

  - Update _static/scheme_template.meta to include [ccpp-table-properties]

2020-10-15 19:12 UTC, climbfuji reviewed
Looks good to me, but I would like to see `CCPPtechnical/source/ConfigBuildOptions.rst` in its final form, if possible. Thank you!

2020-10-15 19:21 UTC, JulieSchramm commented
Here is the PDF file. See Chapter 3.  

[CCPPtechnical.pdf](https://github.com/NCAR/ccpp-doc/files/5387294/CCPPtechnical.pdf)

2020-10-15 19:29 UTC, climbfuji commented
> Here is the PDF file. See Chapter 3.
> 
> [CCPPtechnical.pdf](https://github.com/NCAR/ccpp-doc/files/5387294/CCPPtechnical.pdf)

Thanks. It looks good to me. In the third paragraph of chapter three, we speak about `GFS_physics_driver.F90` etc in a context that includes both SCM and the UFS. These files, however, only exist (yes, they still do) in the UFS, not in the SCM. But maybe we don't need to be that picky.

2020-10-15 19:29 UTC, climbfuji approved these changes

2020-10-15 19:36 UTC, JulieSchramm commented
I saw this sentence and wasn't sure if these files were still used.  They
still exist in the UFS model.  Do you have a suggestion on how to edit the
wording?

On Thu, Oct 15, 2020 at 1:30 PM Dom Heinzeller <notifications@github.com>
wrote:

> *@climbfuji* approved this pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NCAR/ccpp-doc/pull/28#pullrequestreview-509701892>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA3WNU3QSUN2SSICP46QDLTSK5EUPANCNFSM4SSJSRKA>
> .
>

2020-10-15 20:00 UTC, climbfuji commented
Leave it for now, is my suggestion. They will be gone in a month time, and then we have to rewrite the paragraph anyway.

> On Oct 15, 2020, at 1:37 PM, JulieSchramm <notifications@github.com> wrote:
> 
> 
> I saw this sentence and wasn't sure if these files were still used. They
> still exist in the UFS model. Do you have a suggestion on how to edit the
> wording?
> 
> On Thu, Oct 15, 2020 at 1:30 PM Dom Heinzeller <notifications@github.com>
> wrote:
> 
> > *@climbfuji* approved this pull request.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/NCAR/ccpp-doc/pull/28#pullrequestreview-509701892>,
> > or unsubscribe
> > <https://github.com/notifications/unsubscribe-auth/AA3WNU3QSUN2SSICP46QDLTSK5EUPANCNFSM4SSJSRKA>
> > .
> >
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub <https://github.com/NCAR/ccpp-doc/pull/28#issuecomment-709547450>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AB5C2RP4PITM5YXNPZTLUBLSK5FOVANCNFSM4SSJSRKA>.
>

2020-10-16 04:28 UTC, ligiabernardet requested changes
Thanks for the documentation.

Unrelated to the modifications here: I noticed that the PDF (Page 2) is telling viewers to reference this document by citing v4.0. But this PDF does not correspond to any particular version. I think we should remove the citation altogether from the master code (and only have it in documentation associated with a release)

2020-10-16 04:28 UTC, ligiabernardet commented on CCPPtechnical/source/ConfigBuildOptions.rst
> +By default, the code is compiled with CCPP enabled and restricted to CCPP-compliant physics. That is, any parameterization to be called as part of a suite must be available in CCPP. Physics scheme se
I don't think we should talk about ``GFS_physics_driver.F90`` and ``GFS_radiation_driver.F90``as many people will not know what this is. This is historical information.
```suggestion
By default, the code is compiled with CCPP enabled, that is, *CCPP-Framework* and *CCPP-physics* are linked to the executable. Any parameterization to be called as part of a suite must be CCPP-compliant and available in *CCPP-Physics*.  Physics scheme selection and order is determined at runtime by an external suite definition file (SDF; see :numref:`Chapter %s <ConstructingSuite>` for further details on the SDF). 
```

2020-10-16 04:28 UTC, ligiabernardet commented on CCPPtechnical/source/HostSideCoding.rst
> +To establish the link between host model variables and physics scheme variables, the host model must provide metadata information similar to those presented in :numref:`Section %s <MetadataRules>`. T
Word each appears twice in a sentence
```suggestion
To establish the link between host model variables and physics scheme variables, the host model must provide metadata information similar to those presented in :numref:`Section %s <MetadataRules>`. The host model can have multiple metadata files (``.meta``), each with the required ``[ccpp-table-properties]`` section and the related ``[ccpp-arg-table]`` sections. The host model Fortran files contain three-line snippets to indicate the location for insertion of the metadata information contained in the corresponding section in the ``.meta`` file.
```

2020-10-22 19:32 UTC, JulieSchramm commented
Can this be merged?  I resolved the two paragraphs using the GitHub page. I'm not sure about what to do about the links on page 2.  I don't want the links to create a merge conflict every time we have to merge a release branch back to master.

2020-10-22 19:41 UTC, ligiabernardet approved these changes
In this case the citation in the master branch will have to always refer to the latest release.

2020-10-22 19:43 UTC, merged