Feature/update v5 Updates for CCPP v5.0 release
NCAR/ccpp-doc pull request #36
Opened 2020-12-29 17:24 UTC by JulieSchramm

- Add RRFS_v1alpha suite to table in Overview and list in BuildingRunningHostModels chapters
- Remove all references to no_nsst suites
- Update v4 to v5 in links
- Remove an instance of v4 from text for maintainability

html and pdf builds are successful
[CCPPtechnical.pdf](https://github.com/NCAR/ccpp-doc/files/5751546/CCPPtechnical.pdf)

2020-12-29 17:28 UTC, ligiabernardet commented
I will review your changes as soon as time allows.
I believe it is fine to remove no_nsst. The only caveat is that for CCPP v6 we may have to reintroduce it all back in for use with UFS MRW App. However, I do not have a better course of action to propose.

2020-12-31 16:40 UTC, climbfuji requested changes

2020-12-31 16:40 UTC, climbfuji commented on CCPPtechnical/source/Overview.rst
>  and GFS_v16beta, which the target suite at the time for implementation in the
this should be "which is the target suite:

2020-12-31 16:40 UTC, climbfuji commented on CCPPtechnical/source/Overview.rst
> +upcoming operational GFSv16 (it replacing suite GFSv15plus).
"it replaces" ?

2021-01-03 17:41 UTC, ligiabernardet requested changes
Please substitute Fig 1.1 with the most recent diagram (https://app.diagrams.net/#G1ga6gyvoZpwWZBY1s3qPhfOt0jJ4hLpJC)
![General_Dycore_with_CCPP_static_or_dynamic_focus_framework_alternate_dycorephys3](https://user-images.githubusercontent.com/20932610/103484661-cf727d80-4dad-11eb-9b37-eb20a6df4570.png)

Please change "The CCPP can be utilized both with the global and regional configurations of the UFS Atmosphere." to "The CCPP can be utilized both with the global and limited-area configurations of the UFS Atmosphere. CCPP v4.1.0 is the latest release compatible with the global UFS Medium-Range Weather Application. CCPP v5.0.0 is only compatible with the limited-area UFS Short-Range Weather Application".

Section 4.3.4: Given that GFSv16beta is not supported for use with UFS in this release, how about switching this SDF with the one for the SCM?

Section 10.1: Given that GFSv16beta is not supported for use with UFS in this release, suggest changing from: "UFS: GFSv15p2 and GFSv16beta suites" to "UFS: GFSv15p2"

Acronyms: Add RRFS

2021-01-03 17:41 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
>  and GFS_v16beta, which the target suite at the time for implementation in the
```suggestion
and GFS_v16beta, which was the target suite at the time for implementation in the
```

2021-01-03 17:41 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> +upcoming operational GFSv16 (it replacing suite GFSv15plus).
```suggestion
upcoming operational GFSv16 (it replaced suite GFSv15plus).
```

2021-01-03 17:41 UTC, ligiabernardet commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +Documentation `here <https://dtcenter.ucar.edu/GMTB/v5.0/sci_doc/GFS_OZPHYS.html>`_.
```suggestion
Documentation `here <https://dtcenter.ucar.edu/GMTB/v5.0.0/sci_doc/GFS_OZPHYS.html>`_. 
```

2021-01-03 17:41 UTC, ligiabernardet commented on CCPPtechnical/source/ScientificDocRules.inc
> +https://dtcenter.org/GMTB/v5.0/sci_doc.
```suggestion
https://dtcenter.org/GMTB/v5.0.0/sci_doc.
```

2021-01-03 17:41 UTC, ligiabernardet commented on CCPPtechnical/source/ScientificDocRules.inc
> +The HTML result is `here <https://dtcenter.org/GMTB/v5.0/sci_doc/GFS_v15p2_page.html>`_.
```suggestion
The HTML result is `here <https://dtcenter.org/GMTB/v5.0.0/sci_doc/GFS_v15p2_page.html>`_.
```

2021-01-03 17:41 UTC, ligiabernardet commented on CCPPtechnical/source/ScientificDocRules.inc
> +`Here <https://dtcenter.org/GMTB/v5.0/sci_doc/modules.html>`_
```suggestion
`Here <https://dtcenter.org/GMTB/v5.0.0/sci_doc/modules.html>`_
```

2021-01-03 17:41 UTC, ligiabernardet commented on CCPPtechnical/source/conf.py
> +      'maketitle': r'\newcommand\sphinxbackoftitlepage{For referencing this document please use: \newline \break Schramm, J., L. Bernardet, L. Carson, G. Firl, D. Heinzeller, L. Pan, and M. Zhang, 20
```suggestion
      'maketitle': r'\newcommand\sphinxbackoftitlepage{For referencing this document please use: \newline \break Schramm, J., L. Bernardet, L. Carson, G. Firl, D. Heinzeller, L. Pan, and M. Zhang, 2021. CCPP Technical Documentation Release v5.0.0. Available at https://dtcenter.org/GMTB/v5.0.0/ccpp\_tech\_guidev5.0.pdf.}\sphinxmaketitle'
```

2021-01-03 17:41 UTC, ligiabernardet commented on CCPPtechnical/source/conf.py
> +      'maketitle': r'\newcommand\sphinxbackoftitlepage{For referencing this document please use: \newline \break Schramm, J., L. Bernardet, L. Carson, G. Firl, D. Heinzeller, L. Pan, and M. Zhang, 20
While I proposed a change to 5.0.0. I think this section may have to be removed because we are no longer providing the PDF for download in the DTC website.

2021-01-03 17:41 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> +   | PBL                | K-EDMF          | TKE EDMF        | K-EDMF      | saMYNN           | saMYNN                  |
```suggestion
   | PBL                | K-EDMF          | TKE EDMF        | K-EDMF      | MYNN           | MYNN                  |
```
While it is true that the MYNN scheme is scale aware, many other schemes are as well (e.g., GF) but are not denoted as such in this table. To avoid a proliferation of the "sa" qualifier, I suggest we limit it just to SAS, to differentiate it from old SAS scheme(s) that are still in the CCPP code base but are not sa.

2021-01-03 17:41 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> +using the MYNN surface layer parameterization, and employing the Noah-MP LSM.*
```suggestion
and employing the Noah-Multiparameterization (MP) LSM.*
```

2021-01-04 21:03 UTC, climbfuji approved these changes
My comments were addressed, and as far as I can see Ligia's too, but I am going to wait for Ligia's approval before merging.

2021-01-04 22:48 UTC, ligiabernardet requested changes
Thank you for addressing most of my comments. There a few remaining issues to address.

Please all instances of gmtb-help@ucar.eduso users do not go to the de-activated helpdesk but instead go to the two forums (general CCPP) and UFS (UFS Weather Model)

2021-01-04 22:48 UTC, ligiabernardet commented on CCPPtechnical/source/ConstructingSuite.rst
> +RRFS v1beta Suite
We cannot use RRFS v1beta suite because this suite is not supported in CCPP v5 or in UFS WM v2. 
I think my previous comment was not well understood. My suggestion was to replace what was there before (a SDF for FV3 GFSv16beta) with a SDF for SCM GFSv16beta.
Another option is to replace what was there before with a RRFS_v1alpha for SCM or FV3. 
Whatever is decided must be compatible with the description of schemes that is underneath the SDF.

2021-01-04 22:48 UTC, ligiabernardet commented on CCPPtechnical/source/conf.py
> +    #  'maketitle': r'\newcommand\sphinxbackoftitlepage{For referencing this document please use: \newline \break Schramm, J., L. Bernardet, L. Carson, G. Firl, D. Heinzeller, L. Pan, and M. Zhang, 2
We will not post the PDF so the guide will not be available from the DTC website. Can you direct the users to Read The Docs?

2021-01-04 22:48 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> +(RRFS) and differs from the GSD_v1 suite by not using parameterized convection and employing the Noah-MP LSM.*
```suggestion
(RRFS) and differs from the GSD_v1 suite by not using parameterized convection and employing the Noah-Multiparameterization (MP) LSM.*
```

2021-01-05 15:30 UTC, JulieSchramm commented on CCPPtechnical/source/ConstructingSuite.rst
> +RRFS v1beta Suite
"Please all instances of gmtb-help@ucar.edu" This needs a verb.
Suites FV3_GFS_v15p2 and FV3_RRFS_v1alpha are supported for the SRW App release v1, should we be using one of these?

2021-01-05 15:40 UTC, ligiabernardet commented
Please all instances of gmtb-help@ucar.edu and replace them with references
to the Forums (CCPP Forum and UFS WM Forum). The helpdesk has been
deactivated.

If the focus is on RRFS, it is best to use FV3_RRFS_v1alpha than GFSv15p2,
since FV3_RRFS_v1alpha is the primary suite for RRFS. However, it is also
fine to use a suite that works with the SCM, such as GFSv16beta (but use
the SCM one, not the FV3 one).

On Tue, Jan 5, 2021 at 8:30 AM JulieSchramm <notifications@github.com>
wrote:

> *@JulieSchramm* commented on this pull request.
> ------------------------------
>
> In CCPPtechnical/source/ConstructingSuite.rst
> <https://github.com/NCAR/ccpp-doc/pull/36#discussion_r552005147>:
>
> > @@ -151,22 +151,17 @@ Consider the case where a model requires that some subset of physics be called o
>     </suite>
>
>  -------------------------------
> -GFS v16beta Suite
> +RRFS v1beta Suite
>
> "Please all instances of gmtb-help@ucar.edu" This needs a verb.
> Suites FV3_GFS_v15p2 and FV3_RRFS_v1alpha are supported for the SRW App
> release v1, should we be using one of these?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/NCAR/ccpp-doc/pull/36#discussion_r552005147>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE7WQAXYM33EM2AL2NPOVDTSYMWCJANCNFSM4VNNVIQA>
> .
>

2021-01-05 16:56 UTC, JulieSchramm commented
My questions were not addressed.

On Tue, Jan 5, 2021 at 8:40 AM ligiabernardet <notifications@github.com>
wrote:

> Please all instances of gmtb-help@ucar.edu and replace them with
> references
> to the Forums (CCPP Forum and UFS WM Forum). The helpdesk has been
> deactivated.
>
> If the focus is on RRFS, it is best to use FV3_RRFS_v1alpha than GFSv15p2,
> since FV3_RRFS_v1alpha is the primary suite for RRFS. However, it is also
> fine to use a suite that works with the SCM, such as GFSv16beta (but use
> the SCM one, not the FV3 one).
>
> On Tue, Jan 5, 2021 at 8:30 AM JulieSchramm <notifications@github.com>
> wrote:
>
> > *@JulieSchramm* commented on this pull request.
> > ------------------------------
> >
> > In CCPPtechnical/source/ConstructingSuite.rst
> > <https://github.com/NCAR/ccpp-doc/pull/36#discussion_r552005147>:
> >
> > > @@ -151,22 +151,17 @@ Consider the case where a model requires that
> some subset of physics be called o
> > </suite>
> >
> > -------------------------------
> > -GFS v16beta Suite
> > +RRFS v1beta Suite
> >
> > "Please all instances of gmtb-help@ucar.edu" This needs a verb.
> > Suites FV3_GFS_v15p2 and FV3_RRFS_v1alpha are supported for the SRW App
> > release v1, should we be using one of these?
> >
> > —
> > You are receiving this because your review was requested.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/NCAR/ccpp-doc/pull/36#discussion_r552005147>, or
> > unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AE7WQAXYM33EM2AL2NPOVDTSYMWCJANCNFSM4VNNVIQA
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NCAR/ccpp-doc/pull/36#issuecomment-754714256>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA3WNU3JCKM63NHKGFMO4C3SYMXGLANCNFSM4VNNVIQA>
> .
>

2021-01-05 17:07 UTC, ligiabernardet commented
With verb: Please find all instances of gmtb-help@ucar.edu and replace them with references to the Forums (CCPP Forum and UFS WM Forum). The helpdesk has been deactivated. 

To reduce the number of changes, I'd stick with SCM_GFSv16beta. But it is also totally fine to use FV3_RRFS_v1alpha.

If this does not answer your questions, please restate.

2021-01-06 17:19 UTC, ligiabernardet requested changes
Just two tiny changes still to be done.

2021-01-06 17:19 UTC, ligiabernardet commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +* For Fortran coarrays, consult with the DTC helpdesk (https://dtcenter.org/forum/ccpp-user-support).
```suggestion
* For Fortran coarrays, consult with the CCPP Forum (https://dtcenter.org/forum/ccpp-user-support).
```

2021-01-06 17:19 UTC, ligiabernardet commented on CCPPtechnical/source/ScientificDocRules.inc
> +helpdesk at https://dtcenter.org/forum/ccpp-user-support.
```suggestion
Forum at https://dtcenter.org/forum/ccpp-user-support.
```

2021-01-06 17:19 UTC, ligiabernardet commented on CCPPtechnical/source/ScientificDocRules.inc
>  For precise instructions on creating the scientific documentation, contact the DTC
```suggestion
For precise instructions on creating the scientific documentation, contact the CCPP
```

2021-01-06 22:28 UTC, ligiabernardet approved these changes

2021-01-06 22:59 UTC, merged