Documentation for new 3D diagnostic tendencies
NCAR/ccpp-doc pull request #38
Opened 2021-04-13 21:45 UTC by SamuelTrahanNOAA

The gsl/develop branches of UFS, FV3, and ccpp/physics now support 3D diagnostic tendencies for tracers. This PR updates the documentation to match the new method.

Changes written by @SamuelTrahanNOAA by request of @ligiabernardet and @climbfuji

2021-04-13 21:48 UTC, SamuelTrahanNOAA commented
I'm uncertain of the SCM aspects of the documentation, so I'm hoping others can comment on that in their reviews.

2021-04-13 22:17 UTC, ligiabernardet commented
It is good to review this PR, but it should only be merged when the code changes themselves go to master.

2021-04-15 22:27 UTC, ligiabernardet requested changes
Thank you so much for documenting this capability. It is quite easy to follow.

2021-04-15 22:27 UTC, ligiabernardet commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +This example namelist selects all tendencies from microphysics processes, and all tendencies of temperature.
```suggestion
This example namelist selects all tendencies from microphysics processes, and all tendencies of temperature. The naming convention for ``dtend_select`` is explained in the next section.
```

2021-04-15 22:27 UTC, ligiabernardet commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +   dtend_VARIABLE_PROCESS
```suggestion
   dtend_variable_process
```

2021-04-15 22:27 UTC, ligiabernardet commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +You will see lines like this in the model's standard output stream:
```suggestion
After recompiling and running the model, you will see lines like this in the model's standard output stream:
```

2021-04-15 22:27 UTC, ligiabernardet commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +           ``process`` part of ``dtend_variable_process``.
We need some explanation as to why _temperature_ is considered a _process_, when it sounds more like a state variable. 
```suggestion
           ``process`` part of ``dtend_variable_process``. Processes _Production and Loss Rate_, _Ozone Mixing Ratio_, _Temperature_, and _Overhead Ozone Column_ refer to subprocesses within the ozone parameterization.
```

2021-04-16 18:34 UTC, SamuelTrahanNOAA commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +           ``process`` part of ``dtend_variable_process``.
A comment in the code says, "Ozone production from temperature term at model layers."

2021-04-16 18:39 UTC, SamuelTrahanNOAA commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +Another possibility is that the tendencies in question really are zero. The list of "available" tendencies
My inability to get a TKE tendency out of satmedmfvdifq is one such gap.

2021-04-16 18:41 UTC, SamuelTrahanNOAA commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +   | Shallow Convection             | ``gfs_phys``   | ``shalcnv``   | ``dtend(:,:,dtidx(:,index_of_process_scnv))``              |
It only outputs PBL tendency.

2021-04-16 18:42 UTC, SamuelTrahanNOAA commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +           ``process`` part of ``dtend_variable_process``.
I think these are four terms of some equation in the parameterization.

2021-04-16 18:46 UTC, SamuelTrahanNOAA commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +   | **State Variable Or Tracer**                    | **Variable**   | **Associated** | **Array Slice**                              | **Tendency Units**            |
The column heading was unnecessarily long. I have corrected it, and the formatting should be okay now. Please check again.

2021-04-16 18:50 UTC, SamuelTrahanNOAA commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +.. table:: Processes that can change non-chemical tracer and state variables. The third column is the
I added space before each table. How does it look now?

2021-04-16 18:55 UTC, SamuelTrahanNOAA commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +Why are my other tendencies zero, even though the model says they're supported for my configuration?
I swapped the questions and modified the text. Does it look okay now?

2021-04-16 19:29 UTC, SamuelTrahanNOAA commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +tendency is available for all suites.) Then rerun with the desired tendencies enabled.
I rewrote that, and rearranged the later code. It is now explained better.

2021-04-16 19:30 UTC, SamuelTrahanNOAA commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +           ``process`` part of ``dtend_variable_process``.
I updated the tables to clarify that.

2021-04-16 19:33 UTC, SamuelTrahanNOAA commented
> Thank you so much for documenting this capability. It is quite easy to follow.

Hopefully it is still easy to follow now that I've rearranged it.

2021-04-16 19:59 UTC, SamuelTrahanNOAA commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +``dtend_select`` is not recognized. Tendencies are computed in file ``gmtb_scm_output.F90`` in the
The logic to handle `dtend_select` globbing (`*` and `?` characters) is not model-specific. That's the `fglob_list` and `fglob` functions. Grant can lift it out of GFS_typedefs.F90 and put it in SCM. The fill_dtidx and labelling logic use the model data structures, but that shouldn't be hard to fix.

I've never looked at the SCM code though. If you wrote it in Ada or C++, you've a bit more work ahead of you.

2021-04-19 20:12 UTC, JulieSchramm commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +   | **State Variable Or Tracer**                    | **Variable**   | **Associated** | **Array Slice**                              | **Tendency Units**            |
The table header looks good to me.

2021-04-19 20:24 UTC, ligiabernardet commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +Why are my other tendencies zero, even though the model says they're supported for my configuration?
Yes, looks good now.

2021-04-19 20:26 UTC, ligiabernardet commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +``dtend_select`` is not recognized. Tendencies are computed in file ``gmtb_scm_output.F90`` in the
The SCM is in Fortran so your development in GFS_typedefs.F90 should be easy to transfer to the SCM.

2021-04-19 20:29 UTC, ligiabernardet commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +           ``process`` part of ``dtend_variable_process``.
Looks good

2021-04-19 20:33 UTC, ligiabernardet approved these changes
Documentation looks good.
One @grantfirl has this capability working in the SCM, some touch ups will be needed. Including being clear about SCM using time-aggregated tendencies (doc still says instantaneous).

2021-07-21 17:14 UTC, SamuelTrahanNOAA commented
Can this PR be merged now? The code PRs are all merged to their respective central repositories.

2021-07-21 18:56 UTC, merged