First round of updates to technical documentation
NCAR/ccpp-doc pull request #51
Opened 2022-03-17 19:35 UTC by mkavulich

- Add mkavulich to CODEOWNERS file
 - Remove obsolete documentation for host model
 - update CCPP error "flag" 
 - update redefined "debug" flag, and new "verbose" flag in ccpp_prebuild.py

2022-03-24 14:31 UTC, ligiabernardet commented on CODEOWNERS
> +*       @climbfuji @grantfirl @ligiabernardet @mkavulich
I have added @grantfirl to this repo, which I hope will take care of this error

2022-03-27 02:53 UTC, climbfuji requested changes

2022-03-27 02:53 UTC, climbfuji commented on CCPPtechnical/source/BuildingRunningHostModels.rst
> -.. _BuildingRunningHostModels:
I guess that's not needed, because covered in the SCM documentation, and it doesn't really belong here anyway.

2022-03-27 02:53 UTC, climbfuji commented on CCPPtechnical/source/CCPPPreBuild.rst
> +The ``--debug`` command-line argument enables additional checks on array sizes before building the software caps.
```suggestion
The ``--debug`` command-line argument enables additional checks on array sizes inside the auto-generated software caps, prior to entering any of the schemes.
```

2022-04-03 01:31 UTC, climbfuji commented on CCPPtechnical/source/CCPPPreBuild.rst
> +which uses a configuration script located at the specified path. The verbose option can be used for more verbose output from the script.
@ligiabernardet I am making this change in my next PR so that I can merge this PR now.

2022-04-03 01:33 UTC, climbfuji commented
@mkavulich I went ahead and made the changes the @ligiabernardet and I requested so that I can merge this PR and work on my ccpp-doc PR. Hope that's ok. The one additional, minor change that Ligia requested I will make in my PR, too (--suites --> `--suites`).

2022-04-03 01:33 UTC, merged