Updates to Overview/Introduction, fix spelling errors
NCAR/ccpp-doc pull request #56
Opened 2022-05-19 16:05 UTC by mkavulich

- Update Overview for new supported suites and schemes, including links to Scientific Documentation
 - Updates to Introduction to start standardizing the various formats in the doc (bolt, ital, etc.)
 - Fix spelling errors across document

2022-05-19 18:21 UTC, climbfuji approved these changes

2022-05-19 23:33 UTC, ligiabernardet requested changes
Thank you for the great bug fixes, updates, and enhancements.

In particular, thank you for including a good explanation of operational and developmental suites. I am not sure what to do with the concept you introduced of "experimental". You said _*experimental* suites are included in the `ccpp_physics` repository_ but this is not correct because ccpp-physics does not have suites (only schemes). My suggestion is to remove the "experimental" concept altogether, since all suites in the release are either operational or developmental.  However, I get the feeling what you are trying to say is that there are schemes in the repo (and in the released code) that are unsupported. If so, perhaps you can use the word unsupported and refer to the schemes but not to the suites.

Please insert this bold text in the Introduction chapter. 
(it replaced suite GFSv15plus). **CCPP v4.0 was the first release supported for use with the UFS Weather Model, more specifically as part of the UFS Medium-Range Weather (MRW) Application.** The CCPP v4.1 release,

2022-05-19 23:33 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> +   | **Supported hosts** | **SCM/MRW/SRW**  | :g:`**SCM/MRW**` | :g:`**SCM**`   |:g:`**SCM/SRW**`|:g:`**SCM/SRW**`|:g:`**SCM/SRW**`|
GFSv16 is not supported with MRW
```suggestion
   | **Supported hosts** | **SCM/SRW**  | :g:`**SCM/MRW**` | :g:`**SCM**`   |:g:`**SCM/SRW**`|:g:`**SCM/SRW**`|:g:`**SCM/SRW**`|
```

2022-05-19 23:33 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> +   | **Supported hosts** | **SCM/MRW/SRW**  | :g:`**SCM/MRW**` | :g:`**SCM**`   |:g:`**SCM/SRW**`|:g:`**SCM/SRW**`|:g:`**SCM/SRW**`|
There is some issue with the formatting of this line (double asterisks). See https://mike-k-tech-doc.readthedocs.io/en/latest/Overview.html

2022-05-19 23:33 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> +Only the suites that are currently supported in the CCPP are listed in the table. Currently all supported suites use the 2015 Navy Research Laboratory (NRL) `ozone <https://dtcenter.ucar.edu/GMTB/v6.
The future/permanent location for the CCPP v6 SciDoc will be https://dtcenter.ucar.edu/GMTB/v6.0.0, without the "p" in the end. Do you want to fix this now (which will result in broken links) or later?

2022-05-19 23:33 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> +* The RAP scheme is similar to the operational Rapid Refresh (RAP) model physics package, and features Thompson microphysics, `Mellor-Yamada-Nakanishi-Niino (MYNN) EDMF <https://dtcenter.ucar.edu/GMT
I am trying to fix drag appearing twice in the same sentence
```suggestion
* The RAP scheme is similar to the operational Rapid Refresh (RAP) model physics package, and features Thompson microphysics, `Mellor-Yamada-Nakanishi-Niino (MYNN) EDMF <https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/_m_y_n_n_e_d_m_f.html>`_ PBL, `Grell-Freitas (GF) <https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/_c_u__g_f.html>`_ deep convection and shallow convection schemes, RRTMG radiation, `MYNN surface layer (SFL) <https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/_s_f_c__m_y_n_n_s_f_l.html>`_ scheme, `Global Systems Laboratory (GSL) <https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/_g_f_s_drag_suite.html>`_ gravity wave drag scheme, and the `Rapid Update Cycle (RUC) Land Surface Model <https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/_r_u_c_l_s_m.html>`_.
```

2022-05-19 23:33 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> +    release compatible with the global UFS Medium-Range Weather Application and the
```suggestion
    release compatible with the global UFS MRW Application and the
```

2022-05-19 23:33 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> +    limited-area UFS Short-Range Weather Application.  The CCPP
```suggestion
    limited-area UFS SRW Application.  The CCPP
```

2022-05-20 16:27 UTC, mkavulich commented on CCPPtechnical/source/Overview.rst
>  `CCPP Scientific Documentation <https://dtcenter.ucar.edu/GMTB/v5.0.0/sci_doc>`_
@ligiabernardet, I am including a bunch of links to the scientific document below as well. For now I have been pointing to the temporary locations as this makes it easier to ensure that the links are correct, and they can be updated all at once when the scientific documentation is published (it is listed in the issue tracking "to-do" tasks). I think that's a better way to go about it, but if you feel strongly I can make the update to the "future" links now.

2022-05-20 16:31 UTC, mkavulich commented on CCPPtechnical/source/Overview.rst
> +Only the suites that are currently supported in the CCPP are listed in the table. Currently all supported suites use the 2015 Navy Research Laboratory (NRL) `ozone <https://dtcenter.ucar.edu/GMTB/v6.
See my comment above, I'd rather fix it later if that's all right with you.

2022-05-20 16:32 UTC, mkavulich commented
@ligiabernardet I believe I have resolved all your suggestions except for the bit about SciDoc links, let me know what you think. I also re-built the temporary readthedocs for easier viewing: https://mike-k-tech-doc.readthedocs.io/en/latest/Overview.html

2022-05-23 20:32 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
>  `CCPP Scientific Documentation <https://dtcenter.ucar.edu/GMTB/v5.0.0/sci_doc>`_
OK, this is a reasonable way forward

2022-05-23 20:38 UTC, ligiabernardet approved these changes
HI Mike, Thanks for all the updates. I went already and approved the PR but there was one change I requested but could not find in the resulting HTML.  So, if you could this one before merging it would be great.

Please insert this bold text in the Introduction chapter.
(it replaced suite GFSv15plus). **CCPP v4.0 was the first release supported for use with the UFS Weather Model, more specifically as part of the UFS Medium-Range Weather (MRW) Application.** The CCPP v4.1 release,

2022-05-23 20:59 UTC, mkavulich commented
Sorry about missing that first comment! Added it.

2022-05-23 21:00 UTC, merged