Formatting, wording, and link updates, add section on "Standard Names"
NCAR/ccpp-doc pull request #57
Opened 2022-06-02 19:13 UTC by mkavulich

This PR is mostly updates to the "CCPP-Compliant Physics Parameterizations" chapter, with some other miscellaneous fixes

 - Continuing to standardize formatting
 - Wording and grammar fixes, clarifications
 - Updating the template scheme and meta file locations (no longer in ccpp-framework)
 - Use an actual scheme as a DDT example rather than the UFS Weather Model's `GFS_typedefs.meta`, which is a different concept that has not been introduced yet
 - Add section on "Standard Names"

2022-06-02 19:15 UTC, mkavulich commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +A list of available standard names for each host model can be found in
I hope someone can clarify for me whether these documents should still be referenced; are they up-to-date and consistent with the CCPPStandardNames repository?

2022-06-02 19:36 UTC, grantfirl commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +Interstitial modules (*schemename_pre* and *schemename_post*) can be included in a scheme's module if any part of the physics
I don't think that this is the right interpretation of the replaced text. I think that the original text just says that a developer can create *schemename_pre* and/or *schemename_post* schemes should the scheme *schemename* need any scheme-specific calculation performed before or after the scheme, assuming that there is a good reason for such code NOT to be included in the scheme itself, like if the interstitial code is host-specific or otherwise only needed when the scheme is part of a specific suite.

2022-06-02 19:37 UTC, grantfirl commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +Interstitial modules (*schemename_pre* and *schemename_post*) can be included in a scheme's module if any part of the physics
Geez, that was a long sentence. Let me know if it doesn't make sense.

2022-06-02 19:45 UTC, grantfirl commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +A list of available standard names for each host model can be found in
This is a good question. These are DEFINITELY not up-to-date. Since up-to-date versions can be generated by running ccpp_prebuild.py with one of the hosts (as explained in the text), I would argue that is sufficient. Otherwise, someone will need to regenerate them using the release code and push them to the repository.

2022-06-05 14:39 UTC, mkavulich commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +Interstitial modules (*schemename_pre* and *schemename_post*) can be included in a scheme's module if any part of the physics
Thanks, I think I understand. I was confused as to why a different subroutine would be needed sequentially before and/or after the main scheme, but being host-dependent makes sense. I've updated the wording.

2022-06-05 14:39 UTC, mkavulich commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +following subroutines (*entry points*): *_timestep_init*, *_init*, *_run*, *_finalize*,
Done

2022-06-05 14:40 UTC, mkavulich commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +A list of available standard names for each host model can be found in
Thanks for the clarification. I've updated the wording to just have users generate their own PDFs

2022-06-05 18:34 UTC, ligiabernardet requested changes
Thank you for the updated and much improved documentation. I have just a few comments.

2022-06-05 18:34 UTC, ligiabernardet commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +It is recommended that parameterizations be partitioned into the smallest units that will be used independently.
I do not agree with the change from comprised to partitioned. Perhaps processes should be partitioned into parameterizations but  parameterization should not be partitioned. If this is not clear, or not good English, let's think of another way to express it.
```suggestion
It is recommended that parameterizations be comprised of the smallest units that will be used independently.
```

2022-06-05 18:34 UTC, ligiabernardet commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +An up-to-date list of available standard names for each host model can be found by running the CCPP *prebuild* script (described in :numref:`Chapter %s <CCPPPreBuild>`), which will generate a LaTeX s
```suggestion
An up-to-date list of available standard names for a given host model can be found by running the CCPP *prebuild* script (described in :numref:`Chapter %s <CCPPPreBuild>`), which will generate a LaTeX source file that can be compiled to produce a PDF file with all variables 
```

2022-06-05 18:34 UTC, ligiabernardet commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +  using the UFS Weather Model as the host model, tendencies are split in ``GFS_typedefs.meta``
We use UFS Atmosphere in various parts of the document, referring to fv3atm. This is because CCPP is not used in the ocean, waves, or sea ice parts of the UFS Weather Model. I suggest reverting this change.

2022-06-05 18:34 UTC, ligiabernardet commented on CCPPtechnical/source/ParamSpecificOutput.rst
>  These capabilities have been tested and are expected to work with the following suites:
I am wondering if anybody actually tested this and if it will work with the WoFS suite.

2022-06-08 04:50 UTC, mkavulich commented on CCPPtechnical/source/ParamSpecificOutput.rst
>  These capabilities have been tested and are expected to work with the following suites:
I guess that's technically not true for the SRW yet, but it will presumably be tested before the release.

2022-06-08 04:51 UTC, mkavulich commented
@ligiabernardet I think I have addressed all your comments, let me know if you have anything further.

2022-06-08 15:45 UTC, ligiabernardet approved these changes

2022-06-08 18:20 UTC, merged