Update sci doc rules
NCAR/ccpp-doc pull request #59
Opened 2022-06-08 04:57 UTC by mkavulich

This PR is the next "batch" of changes ready for review, but it also includes the changes from #57 so I have opened it as a draft for now to avoid confusion

This PR is mostly updates to the second half of the "CCPP-Compliant Physics Parameterizations" chapter, with some other miscellaneous fixes

 - Continuing to standardize formatting
 - Wording and grammar fixes, clarifications
 - Some more details and explanation about scheme pages
 - Update various file locations
 - Remove some unnecessary detail about starting Doxygen from scratch
 - Update Tech Doc citation

2022-06-09 19:42 UTC, mzhangw commented on CCPPtechnical/source/ScientificDocRules.inc
> +https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/index.html
Please use this address:
https://dtcenter.ucar.edu/GMTB/v6.0.0/sci_doc/index.html

2022-06-09 19:45 UTC, mzhangw commented on CCPPtechnical/source/ScientificDocRules.inc
> +The HTML result of this Doxygen code `can be viewed here <https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/_g_f_s_v16_page.html>`_.
change v6scidoc link

2022-06-09 19:46 UTC, mzhangw commented on CCPPtechnical/source/ScientificDocRules.inc
> +`Here is a list of modules <https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/modules.html>`_
again

2022-06-09 19:46 UTC, ligiabernardet requested changes
Thanks for all these great changes and improvements.

2022-06-09 19:46 UTC, ligiabernardet commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +   The ``physcons`` module in FV3 **should not** be used, as it is specific to that dynamic core and will be removed in the future.
I do not understand this change because physcons is not in FV3 (it is at https://github.com/NCAR/ccpp-physics/blob/main/physics/physcons.F90). I think the original text is correct.

2022-06-09 19:46 UTC, ligiabernardet commented on CCPPtechnical/source/ScientificDocRules.inc
> +https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/index.html
Should we put the final URL here so we do not have to update again? Even though it will be broken for a few more days?

2022-06-09 19:46 UTC, ligiabernardet commented on CCPPtechnical/source/ScientificDocRules.inc
> +The HTML result of this Doxygen code `can be viewed here <https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/_g_f_s_v16_page.html>`_.
Use final URL?

2022-06-09 19:46 UTC, ligiabernardet commented on CCPPtechnical/source/ScientificDocRules.inc
> +`Here is a list of modules <https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/modules.html>`_
Use final URL?

2022-06-09 19:46 UTC, ligiabernardet commented on CCPPtechnical/source/conf.py
> +author = 'J. Schramm, L. Bernardet, L. Carson, G. Firl, \\\ D. Heinzeller, L. Pan, M. Zhang, and M. Kavulich'
I have been thinking about how to handle this. I think we should move Julie's name from the first position. I propose that I take the first position for v6 and, assuming Mike K. continues leading the Tech Doc, he takes over the first position in v7. If you agree, please make this change.

2022-06-09 19:46 UTC, ligiabernardet commented on CCPPtechnical/source/conf.py
> +    'maketitle': r'\newcommand\sphinxbackoftitlepage{For referencing this document please use: \newline \break Schramm, J., L. Bernardet, L. Carson, G. Firl, D. Heinzeller, L. Pan, M. Zhang, and M. K
See previous recommendation wrt author list

2022-06-09 19:55 UTC, mzhangw commented on CCPPtechnical/source/ScientificDocRules.inc
>  #. Have the doxygen executable installed on your computer. For the NOAA
Along with Doxygen, Graphviz  (dot tool for calling graph) and BibTex  (for citation and bibliography)should be installed on local computers.

2022-06-09 21:06 UTC, mkavulich commented on CCPPtechnical/source/ScientificDocRules.inc
> +https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/index.html
@mzhangw I have many web addresses in the technical doc (not just this chapter) that I was waiting to update until those links go live, it is much easier for me to check that I am pointing to the correct locations that way.

2022-06-09 21:19 UTC, mkavulich commented on CCPPtechnical/source/ScientificDocRules.inc
> +https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/index.html
@ligiabernardet I have at least one more set of changes to do, would it be all right to finalize it then? It's one of the last checkboxes on #49 that is still unchecked.

2022-06-09 21:27 UTC, ligiabernardet commented on CCPPtechnical/source/ScientificDocRules.inc
> +https://dtcenter.ucar.edu/GMTB/v6.0.0p/sci_doc/html/index.html
Yes (here and on other placed I flagged)

2022-06-09 21:33 UTC, mkavulich commented on CCPPtechnical/source/conf.py
> +author = 'J. Schramm, L. Bernardet, L. Carson, G. Firl, \\\ D. Heinzeller, L. Pan, M. Zhang, and M. Kavulich'
Thanks, I meant to specifically ask for comments about this change but I forgot. It seems reasonable to me; I also shifted Julie and Laurie to the end since they are no longer actively contributing.

2022-06-09 21:35 UTC, mkavulich commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +   The ``physcons`` module in FV3 **should not** be used, as it is specific to that dynamic core and will be removed in the future.
I had replied to this comment but the comment is lost somehow...

Thanks for pointing this out, I'm not sure how I misunderstood the original context but I have restored the original wording for the most part. I'm keeping it in this "note" block for emphasis.

2022-06-09 23:44 UTC, mkavulich commented on CCPPtechnical/source/ScientificDocRules.inc
>     ./ccpp/framework/scripts/metadata2html.py -c ccpp/config/ccpp_prebuild_config.py
I confirmed this is correct, updated the text to include this information.

2022-06-10 00:12 UTC, mkavulich commented on CCPPtechnical/source/ScientificDocRules.inc
>  #. Have the doxygen executable installed on your computer. For the NOAA
@mzhangw I was able to build the docs locally via Homebrew (with a LOT of dependent packages). The previous instructions include directions for Cheyenne and Hera, but those machines don't have this new "Graphviz" tool. I just removed the Cheyenne/Hera instructions for now, since this shouldn't be needed by too many people (and it can be difficult to view the generated documentation on those machines anyway).

2022-06-10 00:13 UTC, mkavulich commented
@ligiabernardet and @mzhangw thank you for your comments! I believe I have addressed all the comments, let me know if there is anything else.

2022-06-10 03:20 UTC, ligiabernardet approved these changes
Looks good, thanks!

2022-06-10 13:02 UTC, merged