Adding content for stub build and CCPP phases, formatting and style fixes
NCAR/ccpp-doc pull request #61
Opened 2022-06-10 13:21 UTC by mkavulich

- Add section on CCPP stub build
 - Add section on CCPP phases and expand on explanation of parallelization rules and data blocking
 - Update outdated examples using old suites
 - Formatting and style fixes
 - Minor updates to "Host Side Coding" chapter

You can view the latest version of this branch's proposed changes in ReadTheDocs here: https://mike-k-tech-doc.readthedocs.io/en/latest/CompliantPhysicsParams.html

2022-06-13 02:52 UTC, climbfuji requested changes

2022-06-13 02:52 UTC, climbfuji commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +* The *timestep_finalize* phase, which performs post-integration calculations such as computing
tendencies (not tendancies). May also want to mention that this capability is currently unused. I am not aware of any model using `timestep_finalize`.

2022-06-13 02:52 UTC, climbfuji commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +* ``horizontal_dimension`` refers to all (horizontal) grid columns that an MPI process owns/is responsible for, and that are passed to the physics in the *init*, *timestep_init*, *timestep_final*, an
Right now, timestep_final / final will not work - needs to be finalize each time.

2022-06-13 02:52 UTC, climbfuji commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +  * ``horizontal_dimension`` in the metadata tables for the following phases: *init*, *timestep_init*, *timestep_final*, *final*.
Same here.

2022-06-13 17:35 UTC, mkavulich commented
@climbfuji Thanks for your review! I think I have addressed all your comments, let me know if you have anything else.

2022-06-13 22:28 UTC, ligiabernardet requested changes
Thank you again for all the great additions. I left a minot comment.

2022-06-13 22:28 UTC, ligiabernardet commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +In general, physics parameterizations in the CCPP framework are broken down into five *phases*:
The sentence _physics parameterizations in the CCPP framework_ is strange, because there are not parameterizations in the framework. Can you think of a way to rewrite that? Perhaps _CCPP-compliant physical parameterizations can contain one or more of the following phases_

2022-06-27 16:13 UTC, mkavulich commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +In general, physics parameterizations in the CCPP framework are broken down into five *phases*:
Sorry Ligia, I did not notice this final comment. I have changed the wording similar to your suggestion, please let me know if it still needs more work.

2022-06-28 00:57 UTC, merged