Updates to address items listed in issue 63
NCAR/ccpp-doc pull request #65
Opened 2022-11-02 20:47 UTC by mkavulich

- Clean up Glossary and linked terms
 - Replace mentions of forum with GitHub discussions
 - Updates to host side coding based on changes to CCPP Physics
 - Update Code Management for new Application Fork workflow
 - Some miscellaneous fixes

You can view the latest version of this branch's proposed changes in ReadTheDocs here: https://mike-k-tech-doc.readthedocs.io/en/latest/index.html

2022-11-07 02:15 UTC, ligiabernardet requested changes
Thank you for the fixes and upgrades, as well as for adding many more links to the definitions in the glossary. Looks great.
The acronym NEMSfv3gfs is no longer used and should be removed from the list of acronyms.

2022-11-07 02:15 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
>  The CCPP is governed by the groups that contribute to its development. The governance
I suggest a change for the CCPP Physics governance and code mgmt: 
The CCPP Physics code management is collaboratively determined by NOAA, NCAR, and the Navy Research Laboratory (NRL), and the DTC works with EMC and its sponsors to determine :term:`schemes <scheme>` and suites to be included and supported.

2022-11-07 02:15 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> + - *CCPP Physics* https://github.com/NCAR/ccpp-physics/discussions
Is there a reason why the first two bullets are in italics and the remaining ones are not?

2022-11-07 02:15 UTC, ligiabernardet commented on CCPPtechnical/source/ScientificDocRules.inc
> +   use with the :term:`UFS` SRW App and with the CCPP :term:`SCM`.
Not rendering correctly

2022-11-07 02:15 UTC, ligiabernardet commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +and *_finalize*. Each subroutine corresponds to one of the five *phases* of the :term:`CCPP framework` as described above.
```suggestion
and *_finalize*. Each subroutine corresponds to one of the five *phases* of the :term:`CCPP Framework` as described above.
```

2022-11-07 19:01 UTC, mkavulich commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +Schemes in the CCPP are classified into two categories: :term:`*primary* schemes <primary scheme>` and :term:`*interstitial* schemes <interstitial scheme>`.
Unfortunately there's a limitation that the rst specification does not allow for nested formatting. I wanted some way to emphasize the difference between these two scheme types, but perhaps it is just better to let the links speak for themselves.

2022-11-07 19:21 UTC, mkavulich commented
@ligiabernardet Thank you for the thorough reivew! I believe I have addressed all the changes you requested, let me know if you have more comments.

2022-11-08 17:16 UTC, ligiabernardet approved these changes
Thanks for the updates.
The only think I did not see addressed was the removal of NEMSfv3gfs from the list of acronyms.

2022-11-08 19:22 UTC, grantfirl approved these changes
The changes all look OK to me.

2022-11-10 18:28 UTC, merged