Update the chapter on Adding a new scheme to CCPP
NCAR/ccpp-doc pull request #68
Opened 2023-10-26 21:09 UTC by mkavulich

This chapter more thoroughly describes the process of adding a new scheme to CCPP. Includes instructions on logistics (adapting scheme to CCPP-compliance vs using a driver), adding new variables, and debugging a scheme once added. Also included a new glossary definition for "entry point".

2023-10-27 15:28 UTC, ligiabernardet requested changes
Thanks so much for your updates. The Doc is definitely improved.

Is there a way to remove the title of "CCPP v6" since we are beyond v6 now?

2023-10-27 15:28 UTC, ligiabernardet commented on CCPPtechnical/source/AddingNewSchemes.rst
> +Connecting a new scheme to CCPP
Should this be "Connecting an existing scheme to CCPP". The content is about **existing** schemes, new to CCPP, but not _really_ new.

2023-10-27 15:28 UTC, ligiabernardet commented on CCPPtechnical/source/AddingNewSchemes.rst
> +There are a few steps that can be taken to prepare a scheme for addition to CCPP prior to starting the process of implementing it in the CCPP framework:
```suggestion
There are a few steps that can be taken to prepare a scheme for addition to CCPP prior to starting the process of implementing it in the CCPP Framework:
```

2023-10-27 15:28 UTC, ligiabernardet commented on CCPPtechnical/source/AddingNewSchemes.rst
> +There are, broadly speaking, two philosophies for connecting an existing physics scheme to the CCPP framework:
```suggestion
There are, broadly speaking, two philosophies for connecting an existing physics scheme to the CCPP Framework: 
```

2023-10-27 15:28 UTC, ligiabernardet commented on CCPPtechnical/source/AddingNewSchemes.rst
> +There are, broadly speaking, two philosophies for connecting an existing physics scheme to the CCPP framework:
```suggestion
There are, broadly speaking, two approaches for connecting an existing physics scheme to the CCPP framework: 
```

2023-10-27 15:28 UTC, ligiabernardet commented on CCPPtechnical/source/AddingNewSchemes.rst
> +   *Diagram of the methods described in this section*
```suggestion
   *Diagram of the methods described in this section.*
```

2023-10-27 15:28 UTC, ligiabernardet commented on CCPPtechnical/source/AddingNewSchemes.rst
> +Method 1 is the preferred method of adapting a scheme to CCPP. This involves making modifications to the original scheme so that it is CCPP-compliant (see :numref:`Chapter %s <CompliantPhysParams>`),
Why "containing only subroutines that are CCPP entrypoints"? It is still ok to have dependency routines.

2023-10-27 15:28 UTC, ligiabernardet commented on CCPPtechnical/source/AddingNewSchemes.rst
> +Method 1 is the preferred method of adapting a scheme to CCPP. This involves making modifications to the original scheme so that it is CCPP-compliant (see :numref:`Chapter %s <CompliantPhysParams>`),
I suggest removing the last sentence, since that content is present in the next paragraph.

2023-10-27 15:28 UTC, ligiabernardet commented on CCPPtechnical/source/AddingNewSchemes.rst
> +To prepare a scheme for this conversion to CCPP-compliance, the first step is to identify the input variables required for the new scheme and check if they are already available for use in the CCPP.
Adding new variables is not just about adding new schemes. Adding a new variable may be needed for an existing scheme.

2023-10-27 15:28 UTC, ligiabernardet commented on CCPPtechnical/source/AddingNewSchemes.rst
> +     .. note:: The instructions in this chapter assume the user is implementing this scheme in the CCPP Single-Column model (SCM). Other host model variables can be found in different files; see :num
```suggestion
     .. note:: The instructions in this chapter assume the user is implementing this scheme for use in the CCPP Single-Column model (SCM). Other host model variables can be found in different files; see :numref:`Chapter %s <Host-side Coding>` for details
```
Hasn't SCM been previously defined?

2023-10-27 15:28 UTC, ligiabernardet commented on CCPPtechnical/source/AddingNewSchemes.rst
> +Some tips for debugging problems:
This bulleted list is not displaying correctly in the HTML

2023-10-27 16:34 UTC, mkavulich commented on CCPPtechnical/source/AddingNewSchemes.rst
> +To prepare a scheme for this conversion to CCPP-compliance, the first step is to identify the input variables required for the new scheme and check if they are already available for use in the CCPP.
Good point, I have re-worded this beginning part to be more process-agnostic

2023-10-27 16:34 UTC, mkavulich commented on CCPPtechnical/source/AddingNewSchemes.rst
> +Method 1 is the preferred method of adapting a scheme to CCPP. This involves making modifications to the original scheme so that it is CCPP-compliant (see :numref:`Chapter %s <CompliantPhysParams>`),
Thanks for catching that, that's a pretty big distinction! Is the new wording acceptable?

One thing that wasn't clear was whether to write "CCPP entry point" or "CCPP entrypoint"; I've seen it both ways in the docs. I decided to standardize around "entry point" since that seems to be the more common term on the internet when describing subroutines of this nature.

2023-10-27 16:34 UTC, mkavulich commented on CCPPtechnical/source/AddingNewSchemes.rst
> +Connecting a new scheme to CCPP
Good point, though I'm not sure I like adding "existing" to the title of the chapter. I went with simply "Connecting a scheme to CCPP", is that a good compromise?

2023-10-27 16:39 UTC, mkavulich commented
@ligiabernardet thanks for your further comments, I have applied most of your suggested changes and have just a few questions.

The updating of the "v6" links is tough in the main branch because the only more up-to-date scientific docs are SRW-release-specific. Do you think it's appropriate to include those more up-to-date links in this main branch even though they are specific to SRW?

2023-10-31 04:08 UTC, ligiabernardet commented on CCPPtechnical/source/AddingNewSchemes.rst
> +Connecting a new scheme to CCPP
Sure

2023-10-31 04:17 UTC, ligiabernardet commented
> The updating of the "v6" links is tough in the main branch because the only more up-to-date scientific docs are SRW-release-specific. Do you think it's appropriate to include those more up-to-date links in this main branch even though they are specific to SRW?

Please tell me which links you are referring to. Tks

2023-10-31 04:17 UTC, ligiabernardet approved these changes

2023-10-31 14:20 UTC, merged