Updates for CCPP version 7 release
NCAR/ccpp-doc pull request #73
Opened 2024-08-04 02:36 UTC by mkavulich

Updates to the technical documentation in advance of the CCPP v7 release.

Note that not all items in #71 have been completed; I have checked off the items that I was able to finish.

2024-08-04 20:28 UTC, ligiabernardet requested changes
Mike, this is a terrific document. Lots of very helpful information for the user and developer community. Thank you for your updates.

2024-08-04 20:28 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> +`CCPP Scientific Documentation <https://dtcenter.ucar.edu/GMTB/v7.0.0p/sci_doc/index.html>`_
After

> the DTC works with EMC and its sponsors to determine :term:`schemes <scheme>`
> and suites to be included and supported. 

I suggest including the criteria for inclusion discussed at the October 2023 CCPP Physics Code Mgmt Meeting (Slide 3 [here](https://docs.google.com/presentation/d/13QwMEIK3ak6XNi6cLb0FY_vunuVoqiCX/edit#slide=id.g29139aabcfb_1_7)). You may also want to repeat/refer to this information in Chapter 9. 

- The scheme is sufficiently different from schemes already in the repository.
- The scheme is desired by an organization participating in the funding of CCPP or the scheme’s development and/or testing is a funded project of a CCPP-sponsor organization.
- The scheme can be compiled/run with some CCPP-compliant host model.
- Ideally, the scheme is regression tested using at least one host model.
- The scheme is documented and (ideally) published with scientific results.
- The scheme has developer support, or at least a point-of-contact for reviewing code changes.

2024-08-04 20:28 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> +This suite features Thompson Aerosol-Aware microphysics, MYNN-EDMF PBL physics, `Grell-Freitas deep convection <https://dtcenter.ucar.edu/GMTB/v7.0.0p/sci_doc/_c_u__g_f.html>`_, RRTMG radiation, MYNN
GSL drag scheme is now called Orographic Drag Scheme (see https://dtcenter.ucar.edu/GMTB/v7.0.0p/sci_doc/_g_f_s_drag_suite.html)

2024-08-04 20:28 UTC, ligiabernardet commented on CCPPtechnical/source/Overview.rst
> +The CCPP v7.0 release, issued in August 2024, was a major upgrade to physics and the Single-Column Model, particularly with the inclusion of the new `UFS Replay <https://ccpp-scm.readthedocs.io/en/la
We have moved away from the terminology "UFS Replay" to avoid giving the impression that SCM will produce same results as UFS. We not use the terminology "Case Generator".

2024-08-04 20:28 UTC, ligiabernardet commented on CCPPtechnical/source/AddingNewSchemes.rst
> +* Compile code in DEBUG mode (see section 4.3 of the `SCM User's Guide <https://ccpp-scm.readthedocs.io/en/latest/chap_quick.html#compiling-scm-with-ccpp>`_, run through debugger if necessary (gdb, A
Note that this will require a change before the release, to refer to v7

2024-08-16 02:48 UTC, climbfuji requested changes
Thanks for all these updates, very much appreciated. A few tiny changes, the rest looks great.

2024-08-16 02:48 UTC, climbfuji commented on CCPPtechnical/source/AddingNewSchemes.rst
> +     .. note:: As an example, the reader is referred to the `Grell-Freidas convective scheme <https://dtcenter.ucar.edu/GMTB/v7.0.0p/sci_doc/_c_u__g_f.html>`_, which makes use of interstitials to obt
```suggestion
     .. note:: As an example, the reader is referred to the `Grell-Freitas convective scheme <https://dtcenter.ucar.edu/GMTB/v7.0.0p/sci_doc/_c_u__g_f.html>`_, which makes use of interstitials to obtain the previous timestep information.
```

2024-08-16 02:48 UTC, climbfuji commented on CCPPtechnical/source/AddingNewSchemes.rst
> +* Compile code in DEBUG mode (see section 4.3 of the `SCM User's Guide <https://ccpp-scm.readthedocs.io/en/latest/chap_quick.html#compiling-scm-with-ccpp>`_, run through debugger if necessary (gdb, A
```suggestion
* Compile code in DEBUG mode (see section 4.3 of the `SCM User's Guide <https://ccpp-scm.readthedocs.io/en/latest/chap_quick.html#compiling-scm-with-ccpp>`_, run through debugger if necessary (gdb, Linaro/Arm DDT, totalview, …).
```

2024-08-16 02:48 UTC, climbfuji commented on CCPPtechnical/source/CCPPDebug.rst
> +For the UFS models, dedicated debugging schemes have been created by the CCPP developers. These schemes can be found in `physics/Interstitials/UFS_SCM_NEPTUNE/GFS_debug.F90 <https://github.com/NCAR/c
Not directly relevant to the documentation, but the release itself. Every time I used the debugging schemes I have to fix something because it's not been updated. Can you make sure that GFS_debug works before you tag the release code, please?

2024-08-16 02:48 UTC, climbfuji commented on CCPPtechnical/source/CCPPPreBuild.rst
> +<https://dtcenter.ucar.edu/GMTB/v7.0.0p/sci_doc/>`_: typing the subroutine name into the search
Is the `p` correct in `v7.0.0p` ?

2024-08-16 02:48 UTC, climbfuji commented on CCPPtechnical/source/CompliantPhysicsParams.rst
> +  rather than the legacy ``use mpi`` or ``INCLUDE 'mpif.h'``
Maybe it's worth to mention explicitly further down (line 728) that MPI communication is not allowed in the run phase.

2024-08-16 02:48 UTC, climbfuji commented on CCPPtechnical/source/Overview.rst
> +`CCPP Scientific Documentation <https://dtcenter.ucar.edu/GMTB/v7.0.0p/sci_doc/index.html>`_
same here, check if the p in the version is correct please

2024-08-16 02:48 UTC, climbfuji commented on CCPPtechnical/source/Overview.rst
> +    the Finite-Volume Cubed Sphere (FV3) dynamical core, and the The Navy Environmental Prediction System Using the NUMA Core (NEPTUNE).
```suggestion
    the Finite-Volume Cubed Sphere (FV3) dynamical core, and the Navy Environmental Prediction sysTem Using a Nonhydrostatic Engine (NEPTUNE).
```

2024-08-16 02:48 UTC, climbfuji commented on CCPPtechnical/source/Overview.rst
> +    the Finite-Volume Cubed Sphere (FV3) dynamical core, and the The Navy Environmental Prediction System Using the NUMA Core (NEPTUNE).
The acronym was updated a while ago

2024-08-16 02:48 UTC, climbfuji commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +         ichoice   = ichoice_in
I assume lines 545-547 are because the scheme code itself changed for this release

2024-08-16 14:15 UTC, mkavulich commented on CCPPtechnical/source/CCPPPreBuild.rst
> +<https://dtcenter.ucar.edu/GMTB/v7.0.0p/sci_doc/>`_: typing the subroutine name into the search
These links currently point to the draft pages which are at that location. They will be updated once the Scientific Documentation is published

2024-08-16 14:17 UTC, mkavulich commented on CCPPtechnical/source/ParamSpecificOutput.rst
> +         ichoice   = ichoice_in
That's correct, I updated this example based on the latest code since that hadn't been done in a few releases. I didn't actually try this procedure to make sure it still works, I should add that to my list of checks to make.

2024-08-26 02:05 UTC, mkavulich commented on CCPPtechnical/source/CCPPDebug.rst
> +For the UFS models, dedicated debugging schemes have been created by the CCPP developers. These schemes can be found in `physics/Interstitials/UFS_SCM_NEPTUNE/GFS_debug.F90 <https://github.com/NCAR/c
Thanks for mentioning this, it does look like the current capability is broken, we are investigating.

2024-08-29 20:42 UTC, grantfirl commented on CCPPtechnical/source/CCPPDebug.rst
> +For the UFS models, dedicated debugging schemes have been created by the CCPP developers. These schemes can be found in `physics/Interstitials/UFS_SCM_NEPTUNE/GFS_debug.F90 <https://github.com/NCAR/c
https://github.com/ufs-community/ccpp-physics/pull/183 was merged after the deadline for physics PRs to be included in the release. Since the CCPP release is not associated with a release of the UFS, and only uses the SCM, we'd need to get this working in the SCM, but in order to do so, we'd need to bring in more CCPP physics PRs. I'm not sure that we should do this for the release, although I can work on it afterwards. Maybe for a *.1 tag/release?

2024-09-05 15:37 UTC, climbfuji approved these changes

2024-09-05 21:27 UTC, ligiabernardet approved these changes

2024-09-09 20:17 UTC, merged